### ISSUE TITLE
Create basic design for this game

### ISSUE THREAD

**Issue by matejkoncal** [matejkoncal/angry_gardener#2]

**Comment by mgzverky** [comment]
Ok

**Comment by mgzverky** [comment]
ale vajce izmometricky dajak neviem 👎

**Comment by matejkoncal** [comment]
- [ ] Create design for charactes
- [ ] Create map design
- [ ] Create obstackle

**Comment by mgzverky** [comment]
problem to load all graphics

**Comment by matejkoncal** [comment]
Zahri sa na to vysral...
